# Generated by Django 3.2 on 2023-04-01 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_lessons', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Package',
            new_name='Packages',
        ),
    ]
