# Generated by Django 3.2 on 2023-04-01 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_lessons', '0002_rename_package_packages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Lessons',
            new_name='Lesson',
        ),
        migrations.RenameModel(
            old_name='Packages',
            new_name='Package',
        ),
    ]
