# Generated by Django 3.2 on 2023-04-01 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_lessons', '0003_auto_20230401_1026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='sku',
        ),
    ]
