# Generated by Django 3.2 on 2023-04-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_lessons', '0004_remove_package_sku'),
    ]

    operations = [
        migrations.RenameField(
            model_name='package',
            old_name='category',
            new_name='lesson',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image',
        ),
        migrations.RemoveField(
            model_name='package',
            name='image_url',
        ),
        migrations.AlterField(
            model_name='lesson',
            name='friendly_name',
            field=models.CharField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='name',
            field=models.CharField(max_length=254),
        ),
    ]
