# Generated by Django 3.2 on 2023-04-08 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_lessons', '0005_auto_20230407_0904'),
    ]

    operations = [
        migrations.AddField(
            model_name='package',
            name='detail',
            field=models.TextField(blank=True, null=True),
        ),
    ]
