# Generated by Django 3.2 on 2023-04-08 08:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_lessons', '0006_package_detail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='detail',
        ),
        migrations.AddField(
            model_name='package',
            name='detail_1',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='detail_2',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='detail_3',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='detail_4',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='package',
            name='what_you_get',
            field=models.TextField(blank=True),
        ),
    ]
