# Generated by Django 3.2 on 2023-04-08 08:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_lessons', '0007_auto_20230408_0817'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='package',
            name='what_you_get',
        ),
    ]
