# Generated by Django 3.2 on 2023-04-13 20:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_lessons', '0008_remove_package_what_you_get'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.FloatField(default=0),
        ),
    ]
