# Generated by Django 3.2 on 2023-04-19 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tennis_lessons', '0009_alter_package_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='package',
            name='price',
            field=models.DecimalField(decimal_places=0, default=0, max_digits=6),
        ),
    ]
